//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_Chapter15
{
    using System.Workflow.Activities;
    using System.Workflow.ComponentModel;
    using System.Workflow.Runtime;
    using Microsoft.SharePoint.WorkflowActions;
    
    
    public partial class Event_ReviewFT : RootWorkflowActivityWithData
    {
    }
}
